export const FORM_TYPES = {
  INPUT: 'INPUT',
  NUMBER_INPUT: 'NUMBER_INPUT',
  PASSWORD: 'PASSWORD',
  SELECT: 'SELECT',
  CHECKBOX: 'CHECKBOX',
  RADIO_GROUP: 'RADIO_GROUP',
  SEARCH: 'SEARCH',
  DATE_PICKER: 'DATE_PICKER',
  AUTO_COMPLETE: 'AUTO_COMPLETE',
  TEXT_AREA: 'TEXT_AREA'
};
