export const MODAL_WIZARDS = {
  ADD_USER: 'ADD_USER',
  LOGIN: 'LOGIN',
  CATEGORY: 'CATEGORY',
  PRODUCT: 'PRODUCT'
};

export const MODAL_WIZARDS_DEFAULT_TITLE = {
  [MODAL_WIZARDS.ADD_USER]: 'Register',
  [MODAL_WIZARDS.LOGIN]: 'Login',
  [MODAL_WIZARDS.CATEGORY]: 'Category',
  [MODAL_WIZARDS.PRODUCT]: 'Product',
};

export const MODAL_WIZARDS_DEFAULT_ICON = {
  [MODAL_WIZARDS.ADD_USER]: 'user',
  [MODAL_WIZARDS.LOGIN]: 'user',
  [MODAL_WIZARDS.CATEGORY]: 'database',
  [MODAL_WIZARDS.PRODUCT]: 'global',
};
